### PR TITLE
add japanese localization

### PR DESCRIPTION
**Pull request by BrotherSharper**
I noticed that the other moulinette language files are the same, do I need to provide a PR for each of them?

### CODE REVIEW

**Comment by SvenWerlen** [comment]
Hi, 
Thank you for working on these translations! Really appreciate.
I'm using global translation files that are shared by all moulinette modules. I'll create a new repository to make them available for pull requests and will include your file there.

**Comment by SvenWerlen** [comment]
Here it is : https://github.com/SvenWerlen/moulinette-translations
I tested with the translations you did for `moulinette-core` and it seems to work properly.
image

Let me know if you have any question.

**Comment by BrotherSharper** [comment]
Thanks!
I see there is much more left to translate!
I'll get at it as soon as I can

**Comment by SvenWerlen** [comment]
No rush. Any key that is not translated will still show up in English.

**Pull request merged**
